version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/express-app
  hook:
    ApplicationStop:
    - location: script/application_stop.sh
      timeout: 300
      runas: ec2-user 
    BeforeInstall;
    - location: script/before_install.sh
      timeout: 300
      runas: ec2-user 
    ApplicationStart:
    - location: script/application_start.sh
      timeout: 300
      runas: ec2-user 